Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,4 +21,5 @@ jobs:
         run: npx snyk auth ${{ secrets.SNYK_TOKEN }}
 
       - name: Snyk Security Scan
-        run: npx snyk test
+        run: |
+          npx snyk test || (echo "Snyk test failed"; exit 1)
